spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: uml-analyse-inconsistency
      auto-offset-reset: earliest
    topic:
      model-analyze: model.analyze
      inconsistencies-errors: inconsistencies.errors
      inconsistencies-by-client: inconsistencies.by.client
    store-inconsistencies: uml.inconsistencies.client.id

  redis:
      host: localhost
      port: 6379

